ifdef CONFIG_OEM_DEBUG_SUPORT
# oem trace
obj-$(CONFIG_OEM_TRACE_SUPORT) += oem_trace.o
obj-y += boot_mode.o
endif

obj-$(CONFIG_OP_GPL_HELPER) += op_gpl_helper.o
obj-$(CONFIG_OP_STRUCT_OFFSET_HELPER) += op_struct_offset_helper.o
obj-y += coretech/
