#
# Makefile for nfc devices

# 15 Oct 2013, Yuyi <oppo@Independent Group>
# Rewritten to use pn544 driver.

#obj-$(CONFIG_NFC_DEVICES)			+= pn544.o
#obj-$(CONFIG_NFC_DEVICES)			+= p61.o
obj-y			+= pn544.o
obj-y			+= p61.o
#obj-$(CONFIG_NFC_PN533)		+= pn533.o
#obj-$(CONFIG_NFC_WILINK)	+= nfcwilink.o

#ccflags-$(CONFIG_NFC_DEBUG) := -DDEBUG
