#dts-dirs += apm
#dts-dirs += arm
#dts-dirs += cavium
#dts-dirs += qcom

dts-dirs += 15801_DVT
dts-dirs += 15801_PVT
dts-dirs += 15811_PVT
dts-dirs += 15811_PVT2
dts-dirs += 15811_PVT3

subdir-y	:= $(dts-dirs)
